//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICT.Strypes.Business.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICT.Strypes.Business.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Point with id: {0} already exist..
        /// </summary>
        internal static string ChargePointDuplicatedErrorMessage {
            get {
                return ResourceManager.GetString("ChargePointDuplicatedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Point with id: {0} is removed and it can not be updated..
        /// </summary>
        internal static string ChargePointRemovedErrorMessage {
            get {
                return ResourceManager.GetString("ChargePointRemovedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Point status must be one of the following: Available, Blocked, Charging, Removed, Reserved, Unknown.
        /// </summary>
        internal static string ChargePointStatusNotValidErrorMessage {
            get {
                return ResourceManager.GetString("ChargePointStatusNotValidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field can&apos;t be longer than {0} characters..
        /// </summary>
        internal static string FieldMaximumLengthErrorMessage {
            get {
                return ResourceManager.GetString("FieldMaximumLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        internal static string FieldRequiredErrorMessage {
            get {
                return ResourceManager.GetString("FieldRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location with id: {0} already exist..
        /// </summary>
        internal static string LocationDuplicatedErrorMessage {
            get {
                return ResourceManager.GetString("LocationDuplicatedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location with id: {0} not found..
        /// </summary>
        internal static string LocationNotFoundErrorMessage {
            get {
                return ResourceManager.GetString("LocationNotFoundErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location type must be one of the following: Parking, Airport, OnStreet, Unknown..
        /// </summary>
        internal static string LocationTypeNotValidErrorMessage {
            get {
                return ResourceManager.GetString("LocationTypeNotValidErrorMessage", resourceCulture);
            }
        }
    }
}
